set encoding=utf-8
set clipboard+=unnamed
set fenc=utf-8
set showcmd
set laststatus=2
set statusline+=%y
set statusline+=[%{has('multi_byte')&&\&fileencoding!=''?&fileencoding:&encoding}]
set statusline+=%<%F
set ruler
set number
set expandtab
set ignorecase
set smartcase
set incsearch
set wrapscan
set hlsearch
set tabstop=2
set shiftwidth=2
set nobackup
set noswapfile
set autoread
set hidden
set cursorline
set cursorcolumn
set virtualedit=onemore
set smartindent
set visualbell
set showmatch
set laststatus=2
set wildmode=list:longest
colorscheme solarized
set background=dark
nnoremap j gj
nnoremap k gk
syntax enable
call plug#begin('~/.vim/plugged')
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
call plug#end()
